from typing import Any, List, SupportsInt, SupportsFloat, Tuple, Union, Optional

def ordinal(value: Union[str, SupportsInt]) -> str: ...
def intcomma(value: Union[str, SupportsFloat], ndigits: Optional[int] = ...): ...

powers: List[int]
human_powers: Tuple[str, ...]

def intword(value: Union[str, SupportsInt], format: str = ...) -> str: ...
def apnumber(value: Union[str, SupportsInt]) -> str: ...
def fractional(value: Union[str, SupportsFloat]) -> str: ...
def scientific(value: Union[str, SupportsFloat], precision: int = ...) -> str: ...
